name: Sync Staging  Branch
on:
  push:
    branches:
      - main  # Runs whenever there's a commit to the main branch

jobs:  
  sync-staging:    
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main  # Change this to the main branch of your repo if different 
          
      - name: Push changes to staging
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config user.name "siva-vnr"
          git config user.email "siva@superbotics.in"
          git checkout -B staging
          git push https://x-access-token:${PAT_TOKEN}@github.com/siva-vnr/test.git staging --force