name: Sync Staging Branch
on:
  push:
    branches:
      - main  # Runs whenever there's a commit to the main branch

jobs:  
  sync-staging:    
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main
          
      - name: Push changes to staging
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -B staging
          git push https://x-access-token:${PAT_TOKEN}@github.com/siva-vnr/test.git staging --force
          git status
